services:
  web:
    build: .
    ports:
      - "3000:3000"  # Make sure this matches the EXPOSE and app port
    volumes:
      - ./:/app
      - /app/node_modules
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3clear
